//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int OrderId { get; set; }
        public string DeliveryAddress { get; set; }
        public string Country { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public int TransportId { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
